-- ==============================================================================
-- PHARMALAUNCH PRO — COMPLETE DATABRICKS SQL SETUP SCRIPT
-- Catalog: drug_forecasting
-- Schemas: gold (Benchmark/Analytics) and app (Transactional/Operational)
-- ==============================================================================

-- ==============================================================================
-- STEP 1: CREATE CATALOG AND SCHEMAS
-- ==============================================================================
CREATE CATALOG IF NOT EXISTS drug_forecasting;
USE CATALOG drug_forecasting;

CREATE SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS app;

-- ==============================================================================
-- STEP 2: CREATE GOLD SCHEMA TABLES (Analytical & Benchmark Layer)
-- ==============================================================================
USE SCHEMA gold;

-- 1. Gold Bass Features Table
CREATE TABLE IF NOT EXISTS drug_forecasting.gold.bass_features (
    product_id STRING NOT NULL,
    addressable_population DOUBLE,
    estimated_penetration DOUBLE,
    competition_level DOUBLE,
    market_access_level DOUBLE,
    relative_price_index DOUBLE,
    marketing_awareness DOUBLE,
    launch_strength DOUBLE,
    physician_awareness DOUBLE,
    clinical_evidence_strength DOUBLE,
    treatment_familiarity DOUBLE
);

-- 2. Gold Weekly Prescription Adoption Trajectories Table
CREATE TABLE IF NOT EXISTS drug_forecasting.gold.weekly_rx (
    product_id STRING NOT NULL,
    week_since_launch INT NOT NULL,
    weekly_rx DOUBLE,
    cumulative_rx DOUBLE
);

-- 3. Gold Analog 12-Dimensional Clinical & Commercial Features Table
CREATE TABLE IF NOT EXISTS drug_forecasting.gold.analog_features (
    product_id STRING NOT NULL,
    therapeutic_area STRING,
    indication STRING,
    active_ingredient STRING,
    pharmacological_class STRING,
    mechanism_of_action STRING,
    route_of_administration STRING,
    target_population STRING,
    addressable_population DOUBLE,
    competition_level DOUBLE,
    relative_price_index DOUBLE,
    market_access_level DOUBLE,
    clinical_evidence_strength DOUBLE
);

-- ==============================================================================
-- STEP 3: COPY CSV DATA INTO GOLD TABLES
-- (Replace '/Volumes/drug_forecasting/gold/data/' or 's3://...' with your source path)
-- ==============================================================================

-- Ingest Bass Features CSV (bass_final.csv)
COPY INTO drug_forecasting.gold.bass_features
FROM '/Volumes/drug_forecasting/gold/data/bass_final.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS (
    'header' = 'true',
    'inferSchema' = 'true',
    'mergeSchema' = 'true'
)
COPY_OPTIONS ('mergeSchema' = 'true');

-- Ingest Weekly Rx Trajectories CSV (weekly_rx_final.csv)
COPY INTO drug_forecasting.gold.weekly_rx
FROM '/Volumes/drug_forecasting/gold/data/weekly_rx_final.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS (
    'header' = 'true',
    'inferSchema' = 'true',
    'mergeSchema' = 'true'
)
COPY_OPTIONS ('mergeSchema' = 'true');

-- Ingest Analog Clinical & Commercial Features CSV (similarity+analog_features_final.csv)
COPY INTO drug_forecasting.gold.analog_features
FROM '/Volumes/drug_forecasting/gold/data/similarity+analog_features_final.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS (
    'header' = 'true',
    'inferSchema' = 'true',
    'mergeSchema' = 'true'
)
COPY_OPTIONS ('mergeSchema' = 'true');


-- ==============================================================================
-- STEP 4: CREATE APP SCHEMA TABLES (Transactional & Application Layer)
-- ==============================================================================
USE SCHEMA app;

-- 1. Organizations Table
CREATE TABLE IF NOT EXISTS drug_forecasting.app.organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL,
    created_at TIMESTAMP
);

-- 2. Users Table
CREATE TABLE IF NOT EXISTS drug_forecasting.app.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email STRING NOT NULL,
    hashed_password STRING NOT NULL,
    full_name STRING,
    role STRING NOT NULL,
    organization_id BIGINT,
    created_at TIMESTAMP
);

-- 3. Analog Catalog Table (App Schema Replica)
CREATE TABLE IF NOT EXISTS drug_forecasting.app.analog_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id STRING NOT NULL,
    therapeutic_area STRING NOT NULL,
    indication STRING NOT NULL,
    active_ingredient STRING,
    pharmacological_class STRING,
    mechanism_of_action STRING,
    route_of_administration STRING,
    target_population STRING,
    addressable_population DOUBLE,
    competition_level DOUBLE,
    relative_price_index DOUBLE,
    market_access_level DOUBLE,
    clinical_evidence_strength DOUBLE,
    created_at TIMESTAMP
);

-- 4. User Forecast Inputs Table
CREATE TABLE IF NOT EXISTS drug_forecasting.app.user_forecast_inputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    product_id STRING,
    product_name STRING,
    therapeutic_area STRING,
    indication STRING,
    addressable_population DOUBLE,
    estimated_penetration DOUBLE,
    top_k INT,
    w_analog DOUBLE,
    user_inputs_json STRING,
    created_at TIMESTAMP
);

-- 5. Complete Forecast Output Records Table
CREATE TABLE IF NOT EXISTS drug_forecasting.app.forecast_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    user_id BIGINT,
    product_id STRING,
    product_name STRING,
    therapeutic_area STRING,
    indication STRING,
    addressable_population DOUBLE,
    estimated_penetration DOUBLE,
    p_hat DOUBLE,
    q_hat DOUBLE,
    m_hat DOUBLE,
    base_52w_rx DOUBLE,
    bull_52w_rx DOUBLE,
    bear_52w_rx DOUBLE,
    top_k INT,
    w_analog DOUBLE,
    input_json STRING,
    bass_params_json STRING,
    analogs_used_json STRING,
    weekly_forecast_json STRING,
    monthly_forecast_json STRING,
    explanations_json STRING,
    created_at TIMESTAMP
);

-- 6. Actual Launch Rx Comparison Table (Optional Tracking)
CREATE TABLE IF NOT EXISTS drug_forecasting.app.actual_launch_rx (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id STRING NOT NULL,
    week_since_launch INT NOT NULL,
    actual_weekly_rx DOUBLE NOT NULL,
    actual_cumulative_rx DOUBLE NOT NULL,
    recorded_at TIMESTAMP
);

-- ==============================================================================
-- STEP 5: (OPTIONAL) POPULATE APP.ANALOG_PRODUCTS DIRECTLY FROM GOLD.ANALOG_FEATURES
-- ==============================================================================
INSERT INTO drug_forecasting.app.analog_products (
    product_id, therapeutic_area, indication, active_ingredient, pharmacological_class,
    mechanism_of_action, route_of_administration, target_population, addressable_population,
    competition_level, relative_price_index, market_access_level, clinical_evidence_strength, created_at
)
SELECT 
    product_id, therapeutic_area, indication, active_ingredient, pharmacological_class,
    mechanism_of_action, route_of_administration, target_population, addressable_population,
    competition_level, relative_price_index, market_access_level, clinical_evidence_strength, current_timestamp()
FROM drug_forecasting.gold.analog_features
WHERE product_id NOT IN (SELECT product_id FROM drug_forecasting.app.analog_products);
